swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v1/data"

# Paths supported by the server application
paths:
  /load-new-project:
    post:
      operationId: "api.endpoints.data.load_html_pages.load_new_project"
      summary: "Endpoint used to load a new project"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: project_zip
          required: true
          type: file
        - in:  formData
          name: project_name
          required: true
          type: string

      responses:
        200:
          description: "Upload process has been executed successfully"
          schema:
            type: boolean
        202:
          description: "Upload process is still running"
          schema:
            type: boolean
        400:
          description: "Upload process failed"
          schema:
            type: boolean

  /load-project:
    post:
      operationId: "api.endpoints.data.load_html_pages.load_project"
      summary: "Endpoint used to load a new project"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: project_zip
          required: true
          type: file
        - in:  formData
          name: project_name
          required: true
          type: string

      responses:
        200:
          description: "Upload process has been executed successfully"
          schema:
            type: boolean
        202:
          description: "Upload process is still running"
          schema:
            type: boolean
        400:
          description: "Upload process failed"
          schema:
            type: boolean

  /delete-projects:
    post:
      operationId: "api.endpoints.data.delete_projects.delete"
      summary: "Endpoint to delete a list of projects sent by input)"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: project_list
          required: false
          type: array
          items:
            type: string

      responses:
        200:
          description: "Projects deleted successfully"
          schema:
            type: boolean