swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v1"

# Paths supported by the server application
paths:
  /status/{unique_id}:
    get:
      operationId: "api.endpoints.status.status"
      summary: "Get the status of a task"

      consumes:
        - "application/xml"
      produces:
        - "application/json"

      parameters:
        - in:  path
          name: unique_id
          required: true
          type: string

      responses:
        200:
          description: "The json containing all the projects"

