version: "3"

services:
  platform-frontend-html:
    container_name: platform-frontend-html
    image: nginx
    ports:
      - 3500:80
    volumes:
      - ./Platform/admirite-platform:/usr/share/nginx/html
    networks:
      - anita-network
  platform-backend:
    container_name: anita-platform-backend
    image: anita-platform-backend
    build:
      context: .
      dockerfile: platform-backend-dockerfile
    ports:
      - "4500:4500"
    expose:
      - 4500
    environment:
      - PLATFORM_FLASK_HOST=0.0.0.0
      - PLATFORM_FLASK_PORT=4500
    entrypoint: python3
    command: server_platform.py
    depends_on:
      - mysql
    volumes:
      - ./Platform:/Platform
    networks:
      - anita-network
  anita:
    container_name: anita
    image: anita
    ports:
      - "5000:5000"
    expose:
      - 5000
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - MYSQL_DATABASE=anita
      - MYSQL_USER=root
      - MYSQL_PASSWORD=gfT!-@sayUOO
    entrypoint: python3
    command: server.py
    depends_on:
      - celery
      - mysql
    volumes:
      - ./projects/trend-analysis:/trend-analysis
    networks:
      - anita-network
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
    environment:  
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_NODE_PORT: 5672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3
    networks:
      - anita-network
      
  celery:
    container_name: celery
    image: anita
    build: .
    hostname: worker
    entrypoint: celery
    environment:
      - MYSQL_DATABASE=anita
      - MYSQL_USER=root
      - MYSQL_PASSWORD=gfT!-@sayUOO
    command: -A celery_task.celery_app.celery worker --loglevel=info
    volumes:
      - ./projects/trend-analysis:/trend-analysis
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - anita-network
      
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gfT!-@sayUOO
      - MYSQL_DATABASE=anita
      - MYSQL_USER=root
      - MYSQL_PASSWORD=gfT!-@sayUOO
    ports:
      - "3306:3306"
    command: --init-file /data/application/anita-local-20211027.sql
    volumes:
      - mysql-db:/var/lib/mysql
      - ./dumps/anita-local-20211027.sql:/data/application/anita-local-20211027.sql
    networks:
      - anita-network

networks:
  anita-network:
    external: true

volumes:
  mysql-db:
