version: "3"

services:
  platform-frontend-html:
    container_name: platform-frontend-html
    image: nginx
    ports:
      - 3500:80
    volumes:
      - ./Platform/admirite-platform:/usr/share/nginx/html
  platform-backend:
    container_name: anita-platform-backend
    image: anita-platform-backend
    build:
      context: .
      dockerfile: platform-backend-dockerfile
    ports:
      - "4500:4500"
    expose:
      - 4500
    networks:
      - anita-network
    environment:
      - PLATFORM_FLASK_HOST=0.0.0.0
      - PLATFORM_FLASK_PORT=4500
    entrypoint: python3
    command: server_platform.py
    depends_on:
      - mysql
    volumes:
      - ./Platform:/Platform
  anita:
    container_name: anita
    image: anita
    ports:
      - "5000:5000"
    expose:
      - 5000
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - MYSQL_DATABASE=anita
      - MYSQL_USER=root
      - MYSQL_PASSWORD="gfT!-@sayUOO"
    entrypoint: python3
    command: server.py
    depends_on:
      - celery
      - mysql
    volumes:
      - ./ANITA:/ANITA
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
    environment:  
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_NODE_PORT: 5672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3
      
  celery:
    container_name: celery
    image: anita
    build: .
    hostname: worker
    entrypoint: celery
    command: -A celery_task.celery_app.celery worker --loglevel=info
    volumes:
      - ./ANITA:/ANITA
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "gfT!-@sayUOO"
      MYSQL_DATABASE: anita
      MYSQL_USER: root
      MYSQL_PASSWORD: "gfT!-@sayUOO"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
    command: --init-file /data/application/empty_dump.sql
    volumes:
        - ./dumps/empty_dump.sql:/data/application/empty_dump.sql
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
