swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v1/software-quality"

# Paths supported by the server application
paths:
  /delete-project:
    get:
      operationId: "api.endpoints.software_quality.delete.delete_project"
      summary: "Endpoint used to delete a project locally and from the db"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  query
          name: project_name
          required: true
          type: string

      responses:
        200:
          description: "Delete of the project has been executed successfully"
          schema:
            type: boolean

  /delete-projects:
    get:
      operationId: "api.endpoints.software_quality.delete.delete_projects"
      summary: "Endpoint used to delete multiple projects locally and from the db"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: project_list
          required: true
          type: array
          items:
            type: string

      responses:
        200:
          description: "Delete of projects has been executed successfully"
          schema:
            type: boolean

  /delete:
    post:
      operationId: "api.endpoints.software_quality.delete.delete_pages"
      summary: "Endpoint used to delete a project locally and from the db"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: project_name
          required: true
          type: string
        - in: formData
          name: rows
          required: true
          type: array
          items:
            type: string

      responses:
        200:
          description: "Delete of the project has been executed successfully"
          schema:
            type: boolean
        204:
          description: "No table found on db"
          schema:
            type: boolean

  /project:
    get:
      operationId: "api.endpoints.software_quality.get.get_project"
      summary: "Endpoint used to obtain all the data related to a project from the db"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  query
          name: project_name
          required: true
          type: string

      responses:
        200:
          description: "Project retrieved successfully"
          schema:
            type: boolean
