version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - anita

  sonarqube:
    image: sonarqube:7.9.2-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - anita
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
    environment:  
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_NODE_PORT: 5672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3

  db:
    image: postgres
    networks:
      - anita
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  
  db:
    image: mysql
    restart: always
    networks:
      - anita
    environment:
      MYSQL_ROOT_PASSWORD: "gfT!-@sayUOO"
    ports:
      - "127.0.0.1:3307:3307"
    expose:
      - "3307"
    volumes:
      - mysql-db:/var/lib/mysql

networks:
  anita:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  mysql-db:
