version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
    environment:  
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_NODE_PORT: 5672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 15s
      retries: 3