swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  # EXAMPLE OF PATH
  /scraper/vendor/list:
    post:
      operationId: "api.scraper.berlusconi_vendor_list"
      summary: "The people data structure supported by the server application"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      
      parameters:
        - in:  formData
          name: url
          required: true
          type: string
          
      
      responses:
        200:
          description: "Successful read fruit list operation"
          schema:
            type: boolean


  /scraper/product/list:
    post:
      operationId: "api.scraper.berlusconi_product_list"
      summary: "The people data structure supported by the server application"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      
      parameters:
        - in:  formData
          name: url
          required: true
          type: string  
      
      responses:
        200:
          description: "Successful read fruit list operation"
          schema:
            type: boolean

