swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /insights/:
    get:
      operationId: "endpoints.overview.get_insights"
      summary: "Retrieve the following insight: n_markets, n_vendors, n_products, n_reviews"

      produces:
        - "application/json"

      responses:
        200:
          description: "Insights retrieved"
        500:
          description: "Internal server error"
  /top-vendors/:
    get:
      operationId: "endpoints.overview.top_vendors"
      summary: "Retrieve the top vendors of the last month"

      produces:
        - "application/json"

      parameters:
        - in: query
          name: n-vendors
          required: false
          type: integer

      responses:
        200:
          description: "Insights retrieved"
        500:
          description: "Internal server error"
  /sales/:
    get:
      operationId: "endpoints.overview.latest_month_sales"
      summary: "Retrieve the sales of the last month"

      produces:
        - "application/json"

      responses:
        200:
          description: "Sales retrieved"
        500:
          description: "Internal server error"
  /graph/:
    get:
      operationId: "endpoints.graph.get_markets_data"
      summary: "Retrieve the sales of the last month"

      produces:
        - "application/json"

      responses:
        200:
          description: "Sales retrieved"
        500:
          description: "Internal server error"



