swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/market"

# Paths supported by the server application
paths:
  /list/:
    get:
      operationId: "endpoints.market.get_markets"
      summary: "Get all markets available"

      produces:
        - "application/json"

      responses:
        200:
          description: "Markets retrieved"
        500:
          description: "Internal server error"
  /n-products/:
    get:
      operationId: "endpoints.market.get_n_products"
      summary: "Get the number of products for each market"

      produces:
        - "application/json"

      responses:
        200:
          description: "N. products retrieved"
        500:
          description: "Internal server error"