swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/product"

# Paths supported by the server application
paths:
  /ta/sales/:
    get:
      operationId: "endpoints.overview.latest_month_sales"
      summary: "Retrieve the sales of the last month"

      produces:
        - "application/json"

      responses:
        200:
          description: "Sales retrieved"
        500:
          description: "Internal server error"
