swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/v1/conf"

# Paths supported by the server application
paths:
  /sonarqube-setup:
    post:
      operationId: "api.endpoints.conf.sonarqube_setup.setup"
      summary: "Endpoint used to configure sonarqube"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"

      parameters:
        - in:  formData
          name: host
          required: true
          type: string
        - in:  formData
          name: port
          required: true
          type: string
        - in:  formData
          name: token
          required: true
          type: string


      responses:
        200:
          description: "Configuration setup completed"
          schema:
            type: boolean
